import 'package:material_ui/material_ui.dart';

/// `Typography.englishLike2021` with `inherit: true` and explicit sizes.
///
/// `ThemeData.light()` and `.dark()` build their text themes with
/// `inherit: false`, which stops `TextStyle.copyWith` and `merge` from
/// composing in descendants. Merging a theme's text theme over this constant
/// first makes the accessibility overrides apply reliably.
const kMergeableEnglishLike2021 = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'englishLike displayLarge 2021',
    fontSize: 57,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.25,
    height: 1.12,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  displayMedium: TextStyle(
    debugLabel: 'englishLike displayMedium 2021',
    fontSize: 45,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.16,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  displaySmall: TextStyle(
    debugLabel: 'englishLike displaySmall 2021',
    fontSize: 36,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.22,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineLarge: TextStyle(
    debugLabel: 'englishLike headlineLarge 2021',
    fontSize: 32,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.25,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineMedium: TextStyle(
    debugLabel: 'englishLike headlineMedium 2021',
    fontSize: 28,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.29,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineSmall: TextStyle(
    debugLabel: 'englishLike headlineSmall 2021',
    fontSize: 24,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleLarge: TextStyle(
    debugLabel: 'englishLike titleLarge 2021',
    fontSize: 22,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
    height: 1.27,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleMedium: TextStyle(
    debugLabel: 'englishLike titleMedium 2021',
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleSmall: TextStyle(
    debugLabel: 'englishLike titleSmall 2021',
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelLarge: TextStyle(
    debugLabel: 'englishLike labelLarge 2021',
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelMedium: TextStyle(
    debugLabel: 'englishLike labelMedium 2021',
    fontSize: 12,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelSmall: TextStyle(
    debugLabel: 'englishLike labelSmall 2021',
    fontSize: 11,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.45,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodyLarge: TextStyle(
    debugLabel: 'englishLike bodyLarge 2021',
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodyMedium: TextStyle(
    debugLabel: 'englishLike bodyMedium 2021',
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodySmall: TextStyle(
    debugLabel: 'englishLike bodySmall 2021',
    fontSize: 12,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
);
