name: accessibility_ci

on:
  push:
    branches:
      - master
      - develop

jobs:
  verify_accessibility_package:
    name: Accessibility package action
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1

      - name: Installing dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed lib test

      - name: Making sure that there are no analysis warnings or errors
        run: dart analyze --fatal-infos --fatal-warnings lib test

      - name: Runing unit tests
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage

      - name: Making sure that code coverage is 100
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 100
          
      - name: Uploading coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  verify_accessibility_example:
    name: Flutter example
    needs: [verify_accessibility_package]
    runs-on: windows-latest
    defaults:
      run:
        working-directory: example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed .

      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings lib test

      - name: Runing unit, widget and golden tests
        run: flutter test --coverage

      - name: Making sure that code coverage is 100
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 100
          path: example/coverage/lcov.info