name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  verify_accessibility_package:
    name: Accessibility package action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed lib test

      - name: Making sure that there are no analysis warnings or errors
        run: dart analyze --fatal-infos --fatal-warnings lib test

      - name: Running unit tests with coverage
        run: flutter test --coverage

      - name: Making sure that code coverage is 100
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 100
          path: coverage/lcov.info
          exclude: '**/*.g.dart **/generated/** **/locales/**'
          
      - name: Upload main package coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-coverage
          path: coverage/lcov.info

  verify_accessibility_example_basic:
    name: Flutter example basic
    needs: [verify_accessibility_package]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/basic
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
        
      - name: Installing dependencies
        run: flutter pub get
        
      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed .
        
      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings lib test
        
      - name: Running unit, widget and golden tests
        run: flutter test --coverage
        
      - name: Making sure that code coverage is at least 80%
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 80
          path: example/basic/coverage/lcov.info

      - name: Upload basic example coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: basic-coverage
          path: example/basic/coverage/lcov.info

  verify_accessibility_example_with_custom_ui:
    name: Flutter example with custom ui
    needs: [verify_accessibility_package]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/with_custom_ui
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
                
      - name: Installing dependencies
        run: flutter pub get
                
      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed .
                
      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings lib

  verify_accessibility_example_with_multiple_languages:
    name: Flutter example with multiple languages
    needs: [verify_accessibility_package]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/with_multiple_languages
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Making sure the package is formatted
        run: dart format --set-exit-if-changed .

      - name: Making sure that there are no analysis warnings or errors
        run: flutter analyze --fatal-infos --fatal-warnings lib test

      - name: Running unit, widget and golden tests
        run: flutter test --coverage

      - name: Making sure that code coverage is at least 80%
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 80
          path: example/with_multiple_languages/coverage/lcov.info

      - name: Upload multiple languages example coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: multiple-languages-coverage
          path: example/with_multiple_languages/coverage/lcov.info

  upload_coverage:
    name: Upload consolidated coverage to Codecov
    needs: [verify_accessibility_package, verify_accessibility_example_basic, verify_accessibility_example_with_multiple_languages]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download main package coverage
        uses: actions/download-artifact@v4
        with:
          name: main-coverage
          path: coverage/

      - name: Download basic example coverage
        uses: actions/download-artifact@v4
        with:
          name: basic-coverage
          path: coverage/basic/

      - name: Download multiple languages example coverage
        uses: actions/download-artifact@v4
        with:
          name: multiple-languages-coverage
          path: coverage/multiple-languages/

      - name: Upload main package coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: main-package
          fail_ci_if_error: true

      - name: Upload basic example coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/basic/lcov.info
          flags: example-basic
          fail_ci_if_error: true

      - name: Upload multiple languages example coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/multiple-languages/lcov.info
          flags: example-multiple-languages
          fail_ci_if_error: true
